title: Автопарк
description: > # this means to ignore newlines until "baseurl:"
  Проект "Автопарк"
permalink: /index.html
show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
